version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  backend:
    build:
      context: .
      dockerfile: Dockerfile_test
      args:
        NAME: "${NAME}"
        DATABASE_URL: "${TEST_DATABASE_URL}"
    environment:
      NAME: "${NAME}"
      DATABASE_URL: "${TEST_DATABASE_URL}"
    depends_on:
      - db
    links:
      - db