version: '3.3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: "${PORT}"
        NAME: "${NAME}"
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: "${PORT}"
      NAME: "${NAME}"
    restart: always
