version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: "${PORT}"
        NAME: "${NAME}"
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: "${PORT}"
      NAME: "${NAME}"
      CELERY_BROKER_URL: "${CELERY_BROKER_URL}"
      CELERY_RESULT_BACKEND: "${CELERY_BROKER_URL}"
    restart: always
    volumes:
      - static:/usr/src/kwadrop_backend/static
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - db-data:/var/lib/postgresql/data

  worker:
    build: ./
    command: celery worker --app=worker.celery --loglevel=info
    volumes:
      - ./project:/usr/src/app
    environment:
      CELERY_BROKER_URL: "${CELERY_BROKER_URL}"
      CELERY_RESULT_BACKEND: "${CELERY_BROKER_URL}"
    depends_on:
      - backend
      - redis

  redis:
    image: redis:6-alpine

volumes:
  db-data:
  static:

networks:
  default:
    name: "${NAME}_network"
